# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='カテゴリー'),
        ),
    ]
